//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirsProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortfolioEntities : DbContext
    {
        public PortfolioEntities()
            : base("name=PortfolioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Section1> Section1 { get; set; }
        public virtual DbSet<Section2> Section2 { get; set; }
        public virtual DbSet<Section3> Section3 { get; set; }
        public virtual DbSet<Section4> Section4 { get; set; }
        public virtual DbSet<Section5> Section5 { get; set; }
        public virtual DbSet<Section6> Section6 { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
