//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirsProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section4
    {
        public int Id { get; set; }
        public string Profession { get; set; }
        public string AboutPro { get; set; }
    }
}
